### ISSUE TITLE
If the childView is Listview,How can we show the waitView.

### ISSUE THREAD

**Issue by hexiangbing** [ImKarl/WaitView#1]
Hello Blogger，I have question that is If the childView of RootView is the ListView. And the ListView has it's own ItemView. How can we show the item View which has renderend，if I press into the page at the fist Time.

**Comment by imkarl** [comment]
可以通过`WaitViewController.from(mRootView).filter(filter)`对Listview做特殊处理。
比如，替换ListView的Adapter为WaitAdapter，用于显示等待状态。

-----------
You can do special handling of Listview via `WaitViewController.from(mRootView).filter(filter)`.
For example, replace the ListView's Adapter with the WaitAdapter to display the wait state.
[ From Google Translate ]
