### ISSUE TITLE
使用报错

### ISSUE THREAD

**Issue by ghost** [ImKarl/WaitView#2]
![image](https://user-images.githubusercontent.com/35981460/37079705-7c816ac2-221e-11e8-97bc-ca5a791b320d.png)
![image](https://user-images.githubusercontent.com/35981460/37079749-9fdf1d5c-221e-11e8-85d6-d964ab567a2a.png)
ivContent就是一个普通的imageview
报了这个错误，不知道是不是项目中用了butternife框架的原因，谢谢！

**Comment by imkarl** [comment]
确实和butternife有点关系...

先说原因：WaitView在初始化时，会给原来的ImageView外面包一层ViewGroup（即WaitView），并将ImageView的ID设置给ViewGroup，此时通过原ImageView的ID找到的是WaitView。所有报类型转换错误。

解决方法是：在butternife初始化之后，再初始化WaitView
